FROM alpine:3.12

RUN apk add --update \
        mysql-client \
        logrotate

COPY config/dumprotate.txt /var/logrotate.d/dumprotate
COPY mysql-backup.sh /mysql-backup.sh

RUN chmod +x /mysql-backup.sh
RUN ln -s /mysql-backup.sh /etc/periodic/daily/mysql-dump

CMD ["crond", "-f"]
